// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATudwM2obfXlGLDMubKpdNml0VRVOC1JA',
    appId: '1:796228234054:web:556e02ce6da1a40a5a1347',
    messagingSenderId: '796228234054',
    projectId: 'testytb-ac550',
    authDomain: 'testytb-ac550.firebaseapp.com',
    databaseURL: 'https://testytb-ac550-default-rtdb.firebaseio.com',
    storageBucket: 'testytb-ac550.appspot.com',
    measurementId: 'G-5ZDQ7FKP2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCW2wHfN4Q3VE6HgDEv-kw1uEWtf3goK0',
    appId: '1:796228234054:android:31e4444a10de69c95a1347',
    messagingSenderId: '796228234054',
    projectId: 'testytb-ac550',
    databaseURL: 'https://testytb-ac550-default-rtdb.firebaseio.com',
    storageBucket: 'testytb-ac550.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx0X0T8pIWCeH1e2qRAaXVT9MkwqYhWPU',
    appId: '1:796228234054:ios:65705ac6f31f9e755a1347',
    messagingSenderId: '796228234054',
    projectId: 'testytb-ac550',
    databaseURL: 'https://testytb-ac550-default-rtdb.firebaseio.com',
    storageBucket: 'testytb-ac550.appspot.com',
    iosBundleId: 'com.example.btl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx0X0T8pIWCeH1e2qRAaXVT9MkwqYhWPU',
    appId: '1:796228234054:ios:9288275879a44a2d5a1347',
    messagingSenderId: '796228234054',
    projectId: 'testytb-ac550',
    databaseURL: 'https://testytb-ac550-default-rtdb.firebaseio.com',
    storageBucket: 'testytb-ac550.appspot.com',
    iosBundleId: 'com.example.btl.RunnerTests',
  );
}
