// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB36k78z9ILH72cIxLzss8klPONxutCWnQ',
    appId: '1:564893514155:web:e5357e4f0e05639a723aee',
    messagingSenderId: '564893514155',
    projectId: 'shopmb-33a2f',
    authDomain: 'shopmb-33a2f.firebaseapp.com',
    storageBucket: 'shopmb-33a2f.appspot.com',
    measurementId: 'G-1LXLV6L9GN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY3z0nLKD8ombXNNXJJzX19ILSb0GBf1c',
    appId: '1:564893514155:android:1a6111c6b39c29e7723aee',
    messagingSenderId: '564893514155',
    projectId: 'shopmb-33a2f',
    storageBucket: 'shopmb-33a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMchml8bNWPwh4FDAjcN-gI48Bg5b5zY',
    appId: '1:564893514155:ios:d35f4d83d6252c41723aee',
    messagingSenderId: '564893514155',
    projectId: 'shopmb-33a2f',
    storageBucket: 'shopmb-33a2f.appspot.com',
    iosBundleId: 'com.example.btl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMchml8bNWPwh4FDAjcN-gI48Bg5b5zY',
    appId: '1:564893514155:ios:2047046727bc039e723aee',
    messagingSenderId: '564893514155',
    projectId: 'shopmb-33a2f',
    storageBucket: 'shopmb-33a2f.appspot.com',
    iosBundleId: 'com.example.btl.RunnerTests',
  );
}
